services:
  api:
    build:
      context: .
    container_name: marketAPI
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    networks:
      - messenger-network
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: pollux
      POSTGRES_USER: pollux
      POSTGRES_DB: messenger
      TZ: Europe/Samara
      PGTZ: Europe/Samara
    ports:
      - "5442:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: 128mb
    networks:
      - messenger-network

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - messenger-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge